# Generated by Django 3.2.14 on 2024-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_itemid_cartitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartItems',
        ),
        migrations.AddField(
            model_name='order',
            name='cartItems',
            field=models.TextField(default=''),
        ),
    ]
